#!/usr/bin/env python3
# scripts/porting/agents-to-toml.py — Claude agent definition → Codex agent
# TOML converter (CODEX_PORT_PLAN Phase 3, WI 3.3).
#
# Converts `agents/*.md` (Claude frontmatter + body) into
# `.codex/agents/<name>.toml` per the capability map row "Agent tool / named
# subagents" (project defs: `name`, `description`, `developer_instructions`,
# `model`, `sandbox_mode`):
#
#   name                    ← frontmatter `name:` (fallback: file stem)
#   description             ← frontmatter `description:`
#   developer_instructions  ← the markdown body, verbatim
#   model                   ← frontmatter `model:`; `model: inherit` → OMIT
#                             (inheriting the parent model is Codex's default)
#
# NOT TRANSLATABLE (emitted to the stdout degradations section the porting
# agent pastes into the parity table):
#   tools:   — Codex has NO per-agent tools-allowlist enforcement
#   hooks:   — Codex agents have NO per-agent frontmatter hooks; hook
#              delivery is .codex/hooks.json (see hooks-translate.py)
#   any other unrecognized frontmatter key (conservative: surfaced, never
#   silently dropped)
#
# Output is tomllib-parseable (self-validated when tomllib is available,
# Python >= 3.11). Python 3 stdlib only.
#
# USAGE
#   agents-to-toml.py <agent.md> [--out <file.toml>]
#   agents-to-toml.py <agent.md>... --out-dir <dir>
#
# Exit codes: 0 = converted, 1 = input/parse/self-validation error, 2 = usage.

import argparse
import json
import os
import re
import sys

TRANSLATED_KEYS = {"name", "description", "model"}
DEGRADATION_REASONS = {
    "tools": "Codex enforces no per-agent tools allowlist (capability map: "
             "'NO tools: allowlist enforcement') — documented degradation; "
             "record in the parity table",
    "hooks": "Codex agents carry no per-agent frontmatter hooks — deliver "
             "via .codex/hooks.json (hooks-translate.py) instead",
}
GENERIC_DEGRADATION = ("no Codex agent-TOML field for this key — documented "
                       "degradation; record in the parity table")

RE_TOP_KEY = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):[ \t]*(.*)$")


def parse_agent_md(path):
    """Parse a Claude agent .md into (frontmatter: dict[str, str], body).

    Frontmatter values are raw strings; a key introducing an indented block
    (e.g. `hooks:`) collects the block lines into its value (newline-joined),
    which is enough for degradation reporting — blocks are never translated.
    """
    with open(path, encoding="utf-8") as fh:
        text = fh.read()

    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        raise ValueError("%s: no frontmatter (expected leading ---)" % path)
    fm_end = None
    for i in range(1, len(lines)):
        if lines[i].strip() == "---":
            fm_end = i
            break
    if fm_end is None:
        raise ValueError("%s: unterminated frontmatter" % path)

    frontmatter = {}
    order = []
    current_key = None
    for raw in lines[1:fm_end]:
        if raw.strip() == "":
            continue
        m = RE_TOP_KEY.match(raw)
        if m and not raw.startswith((" ", "\t")):
            current_key = m.group(1)
            frontmatter[current_key] = m.group(2).strip()
            order.append(current_key)
        elif current_key is not None:
            # indented continuation → block content under current_key
            frontmatter[current_key] += ("\n" if frontmatter[current_key]
                                         else "") + raw
        else:
            raise ValueError("%s: unparseable frontmatter line: %r"
                             % (path, raw))

    body = "\n".join(lines[fm_end + 1:]).lstrip("\n")
    return frontmatter, order, body


def toml_multiline(s):
    """Render s as a TOML multi-line basic string (escaped, parse-safe)."""
    esc = s.replace("\\", "\\\\")
    # break any run of three-plus quotes (max two consecutive raw quotes are
    # allowed inside a multi-line basic string)
    esc = esc.replace('"""', '""\\"')
    if esc.endswith('"'):
        esc = esc[:-1] + '\\"'
    # escape control chars TOML forbids raw (tab and newline are fine)
    esc = "".join(
        ch if ch in ("\n", "\t") or ord(ch) >= 0x20 else "\\u%04x" % ord(ch)
        for ch in esc)
    return '"""\n' + esc + '"""'


def render_toml(name, description, model, body):
    out = []
    out.append("# Generated by scripts/porting/agents-to-toml.py — Codex")
    out.append("# subagent definition converted from a Claude agents/*.md.")
    out.append("name = %s" % json.dumps(name))
    out.append("description = %s" % json.dumps(description))
    if model:
        out.append("model = %s" % json.dumps(model))
    out.append("developer_instructions = %s" % toml_multiline(body))
    return "\n".join(out) + "\n"


def convert_one(path, out_path, degradations):
    frontmatter, order, body = parse_agent_md(path)

    stem = os.path.splitext(os.path.basename(path))[0]
    name = frontmatter.get("name", "").strip() or stem
    description = frontmatter.get("description", "").strip()
    model = frontmatter.get("model", "").strip()
    if model.lower() == "inherit":
        # `model: inherit` → omit `model` entirely (Codex default behavior)
        model = ""

    for key in order:
        if key in TRANSLATED_KEYS:
            continue
        reason = DEGRADATION_REASONS.get(key, GENERIC_DEGRADATION)
        value = frontmatter[key]
        summary = value if "\n" not in value else (
            "(block, %d lines)" % (value.count("\n") + 1))
        degradations.append("%s: %s: %s — %s" % (path, key, summary, reason))

    toml_text = render_toml(name, description, model, body)

    # self-validate when the stdlib parser exists (Python >= 3.11)
    try:
        import tomllib
        parsed = tomllib.loads(toml_text)
        for field in ("name", "description", "developer_instructions"):
            if not parsed.get(field):
                raise ValueError("field %r empty after render" % field)
    except ModuleNotFoundError:
        pass  # pre-3.11 stdlib: the test suite validates instead

    out_dir = os.path.dirname(os.path.abspath(out_path))
    os.makedirs(out_dir, exist_ok=True)
    tmp = out_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(toml_text)
    os.replace(tmp, out_path)
    print("converted %s -> %s" % (path, out_path))


def main(argv=None):
    parser = argparse.ArgumentParser(
        description="Convert Claude agents/*.md to Codex .codex/agents "
                    "TOML.")
    parser.add_argument("inputs", nargs="+", help="agent .md file(s)")
    parser.add_argument("--out", help="output .toml path (single input only)")
    parser.add_argument("--out-dir",
                        help="output directory (writes <name>.toml per "
                             "input; e.g. <target>/.codex/agents)")
    args = parser.parse_args(argv)

    if args.out and args.out_dir:
        parser.error("--out and --out-dir are mutually exclusive")
    if args.out and len(args.inputs) != 1:
        parser.error("--out requires exactly one input")
    if not args.out and not args.out_dir:
        parser.error("one of --out / --out-dir is required")

    degradations = []
    for path in args.inputs:
        if not os.path.isfile(path):
            print("ERROR: not a file: %s" % path, file=sys.stderr)
            return 1
        if args.out:
            out_path = args.out
        else:
            stem = os.path.splitext(os.path.basename(path))[0]
            out_path = os.path.join(args.out_dir, stem + ".toml")
        try:
            convert_one(path, out_path, degradations)
        except (ValueError, OSError) as e:
            print("ERROR: %s" % e, file=sys.stderr)
            return 1

    print("")
    if degradations:
        print("DEGRADATIONS — not translatable to Codex agent TOML (paste "
              "into the parity table):")
        for d in degradations:
            print("  - %s" % d)
    else:
        print("DEGRADATIONS: none")
    return 0


if __name__ == "__main__":
    sys.exit(main())
