#!/bin/bash
# test-run-plan-sync-pr-body-progress.sh — Unit tests for
# skills/run-plan/scripts/sync-pr-body-progress.sh.
#
# Issue #212: extract Phase 4 PR-body progress sync from /run-plan
# SKILL.md prose into a helper script with a conformance gate. This test
# locks the helper's behaviour so the orchestrator can't silently freeze
# the PR body again (past failure: PR #211).
#
# Coverage (7 cases per spec):
#   1. Splice with markers present
#   2. Idempotency (re-run produces byte-identical output, no second edit)
#   3. Markers absent (NOTICE → exit 0, no gh pr edit invoked)
#   4. PR absent (gh pr view fails → NOTICE → exit 0, no edit)
#   5. gh edit fails (WARNING → exit 0)
#   6. Preserve user prose outside markers
#   7. Plan file missing (ERROR → exit 1)
#
# Run from repo root: bash tests/test-run-plan-sync-pr-body-progress.sh

set -u

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
SCRIPT="$REPO_ROOT/skills/run-plan/scripts/sync-pr-body-progress.sh"
MOCK_GH="$REPO_ROOT/tests/mocks/mock-gh.sh"

if [ ! -x "$SCRIPT" ]; then
  echo "FAIL: $SCRIPT missing or not executable" >&2
  exit 1
fi
if [ ! -x "$MOCK_GH" ]; then
  echo "FAIL: $MOCK_GH missing or not executable" >&2
  exit 1
fi

WORK="/tmp/zskills-tests/$(basename "$REPO_ROOT")/sync-pr-body-progress"
rm -rf "$WORK"
mkdir -p "$WORK"

PASS_COUNT=0
FAIL_COUNT=0

pass() { printf '\033[32m  PASS\033[0m %s\n' "$1"; PASS_COUNT=$((PASS_COUNT+1)); }
fail() { printf '\033[31m  FAIL\033[0m %s\n' "$1"; FAIL_COUNT=$((FAIL_COUNT+1)); }

# Helper: prep an isolated state dir for mock-gh per case.
new_state_dir() {
  local label="$1"
  local d="$WORK/state-$label"
  rm -rf "$d"
  mkdir -p "$d"
  echo "$d"
}

# Helper: write a canned mock-gh response for key/call-number.
# Args: $1=state_dir, $2=key, $3=call_num, $4=stdout, $5=stderr, $6=exit
canned() {
  local sd="$1" key="$2" n="$3" out="$4" err="$5" rc="$6"
  if [ -n "$out" ]; then printf '%s' "$out" > "$sd/$key.$n.stdout"; fi
  if [ -n "$err" ]; then printf '%s' "$err" > "$sd/$key.$n.stderr"; fi
  printf '%s' "$rc" > "$sd/$key.$n.exit"
}

# Helper: write a stub plan file with a progress tracker.
write_plan() {
  local path="$1"
  cat > "$path" <<'PLAN'
# Sample plan

## Progress Tracker

| Phase | Status | Commit | Notes |
|-------|--------|--------|-------|
| 1: Setup | ✅ Done | abc1234 | groundwork |
| 2: Impl  | ✅ Done | def5678 | core feature |
| 3: Test  | 🟡 In Progress | | wired up |
PLAN
}

echo "=== sync-pr-body-progress.sh tests ==="

# ---------------------------------------------------------------
# Case 1: Splice with markers present
# ---------------------------------------------------------------
SD=$(new_state_dir 1)
PLAN_FILE="$WORK/plan-1.md"
write_plan "$PLAN_FILE"

PR_BODY_INITIAL="## Plan: Sample

<!-- run-plan:progress:start -->
**Phases completed:**
1: Setup ✅ Done abc1234 groundwork
<!-- run-plan:progress:end -->

**Report:** see audit.

---
Generated by /run-plan"

# Call 1: gh pr view → success, returns PR_BODY_INITIAL.
canned "$SD" pr_view 1 "$PR_BODY_INITIAL" "" 0
# Call 1: gh pr edit → success, no output, exit 0.
canned "$SD" pr_edit 1 "" "" 0

OUT=$(MOCK_GH_STATE_DIR="$SD" GH_BIN_OVERRIDE="$MOCK_GH" \
  bash "$SCRIPT" --pr 999 --plan-file "$PLAN_FILE" --branch test 2>&1)
RC=$?

if [ "$RC" -ne 0 ]; then
  fail "1: exit code expected 0, got $RC (output: $OUT)"
elif ! grep -q "Synced PR #999" <<< "$OUT"; then
  fail "1: stdout missing 'Synced PR #999' (output: $OUT)"
elif [ ! -f "$SD/pr_edit.1.stdout" ] && [ ! -f "$SD/pr_edit.count" ]; then
  fail "1: gh pr edit was never invoked"
else
  # Read what pr edit was called with — the new body must be in the
  # --body-file argument. We verify content by replaying the spliced body.
  EDIT_INVOKE=$(grep '^pr_edit' "$SD/_invocations.log" | head -1)
  if [[ "$EDIT_INVOKE" != *"--body-file"* ]]; then
    fail "1: pr edit not invoked with --body-file (invoke: $EDIT_INVOKE)"
  else
    # Extract the body-file path and verify content
    BODY_PATH=$(echo "$EDIT_INVOKE" | grep -oE -- '--body-file [^ ]+' | awk '{print $2}')
    if [ ! -f "$BODY_PATH" ]; then
      # The temp file is cleaned up by the helper's trap on exit — we
      # can't read it post-hoc. So instead, verify the spliced result
      # by re-running with the SAME helper logic and checking the
      # produced "Synced" message + idempotency Case 2.
      pass "1: splice with markers present (edit invoked w/ --body-file)"
    else
      if grep -q "2: Impl" "$BODY_PATH"; then
        pass "1: splice with markers present (new tracker row visible)"
      else
        fail "1: spliced body missing new tracker rows"
      fi
    fi
  fi
fi

# ---------------------------------------------------------------
# Case 2: Idempotency — re-running with the same tracker leaves the body
# byte-identical. We mock gh pr view to return a body that ALREADY
# contains the canonical spliced output, then assert no gh pr edit is
# invoked (early-exit path).
# ---------------------------------------------------------------
SD=$(new_state_dir 2)
PLAN_FILE="$WORK/plan-2.md"
write_plan "$PLAN_FILE"

# Generate the canonical expected body by inlining the same regex the
# helper uses. The progress block is "**Phases completed:**\n<rows>" with
# rows derived from "^\| .* \| ✅" lines, pipes stripped, whitespace
# collapsed.
EXPECTED_PHASES=$(grep -E '^\| .* \| ✅' "$PLAN_FILE" | sed 's/|//g' | awk '{$1=$1};1')
CANONICAL_BODY="## Plan: Sample

<!-- run-plan:progress:start -->
**Phases completed:**
$EXPECTED_PHASES
<!-- run-plan:progress:end -->

**Report:** see audit."

# Call 1: gh pr view returns the canonical body (already in sync).
canned "$SD" pr_view 1 "$CANONICAL_BODY" "" 0
# NO canned response for pr_edit — if the helper invokes it, mock-gh
# exits 99 (loud failure).

OUT=$(MOCK_GH_STATE_DIR="$SD" GH_BIN_OVERRIDE="$MOCK_GH" \
  bash "$SCRIPT" --pr 1000 --plan-file "$PLAN_FILE" --branch test 2>&1)
RC=$?

if [ "$RC" -ne 0 ]; then
  fail "2: idempotency — exit expected 0, got $RC (output: $OUT)"
elif ! grep -q "already in sync" <<< "$OUT"; then
  fail "2: idempotency — stdout missing 'already in sync' (output: $OUT)"
elif grep -q '^pr_edit' "$SD/_invocations.log" 2>/dev/null; then
  fail "2: idempotency — gh pr edit was unexpectedly invoked"
else
  pass "2: idempotency (no edit when body already synced)"
fi

# ---------------------------------------------------------------
# Case 3: Markers absent in PR body → NOTICE → exit 0, NO pr edit invoked.
# ---------------------------------------------------------------
SD=$(new_state_dir 3)
PLAN_FILE="$WORK/plan-3.md"
write_plan "$PLAN_FILE"

NO_MARKER_BODY="## Hotfix PR

This PR was opened manually, no /run-plan markers here.
Bug fix for #999."

canned "$SD" pr_view 1 "$NO_MARKER_BODY" "" 0
# NO canned response for pr_edit — helper must not invoke it.

OUT=$(MOCK_GH_STATE_DIR="$SD" GH_BIN_OVERRIDE="$MOCK_GH" \
  bash "$SCRIPT" --pr 1001 --plan-file "$PLAN_FILE" --branch hotfix 2>&1)
RC=$?

if [ "$RC" -ne 0 ]; then
  fail "3: markers absent — exit expected 0, got $RC (output: $OUT)"
elif ! grep -q "NOTICE.*markers not found" <<< "$OUT"; then
  fail "3: markers absent — missing 'NOTICE: markers not found' in stderr (output: $OUT)"
elif grep -q '^pr_edit' "$SD/_invocations.log" 2>/dev/null; then
  fail "3: markers absent — gh pr edit unexpectedly invoked"
else
  pass "3: markers absent (NOTICE, no edit)"
fi

# ---------------------------------------------------------------
# Case 4: PR absent — gh pr view fails (exit 1) → NOTICE → exit 0, no edit
# ---------------------------------------------------------------
SD=$(new_state_dir 4)
PLAN_FILE="$WORK/plan-4.md"
write_plan "$PLAN_FILE"

canned "$SD" pr_view 1 "" "could not find pull request" 1
# No pr_edit canned — must not be invoked.

OUT=$(MOCK_GH_STATE_DIR="$SD" GH_BIN_OVERRIDE="$MOCK_GH" \
  bash "$SCRIPT" --pr 9999 --plan-file "$PLAN_FILE" --branch ghost 2>&1)
RC=$?

if [ "$RC" -ne 0 ]; then
  fail "4: PR absent — exit expected 0, got $RC (output: $OUT)"
elif ! grep -q "NOTICE.*gh pr view #9999 failed" <<< "$OUT"; then
  fail "4: PR absent — missing NOTICE line (output: $OUT)"
elif grep -q '^pr_edit' "$SD/_invocations.log" 2>/dev/null; then
  fail "4: PR absent — gh pr edit unexpectedly invoked"
else
  pass "4: PR absent (NOTICE, no edit)"
fi

# ---------------------------------------------------------------
# Case 5: gh edit fails (auth/network) → WARNING → exit 0
# ---------------------------------------------------------------
SD=$(new_state_dir 5)
PLAN_FILE="$WORK/plan-5.md"
write_plan "$PLAN_FILE"

PR_BODY_INITIAL="## Plan: Sample

<!-- run-plan:progress:start -->
**Phases completed:**
old content
<!-- run-plan:progress:end -->"

canned "$SD" pr_view 1 "$PR_BODY_INITIAL" "" 0
canned "$SD" pr_edit 1 "" "HTTP 401: bad credentials" 1

OUT=$(MOCK_GH_STATE_DIR="$SD" GH_BIN_OVERRIDE="$MOCK_GH" \
  bash "$SCRIPT" --pr 1002 --plan-file "$PLAN_FILE" --branch test 2>&1)
RC=$?

if [ "$RC" -ne 0 ]; then
  fail "5: gh edit fails — exit expected 0, got $RC (output: $OUT)"
elif ! grep -q "WARNING.*gh pr edit #1002 failed" <<< "$OUT"; then
  fail "5: gh edit fails — missing WARNING line (output: $OUT)"
else
  pass "5: gh edit fails (WARNING, exit 0)"
fi

# ---------------------------------------------------------------
# Case 6: Preserve user prose outside markers byte-identical post-splice.
# Strategy: capture the body-file arg passed to gh pr edit and diff
# against the original body with ONLY the marker-enclosed region replaced.
# ---------------------------------------------------------------
SD=$(new_state_dir 6)
PLAN_FILE="$WORK/plan-6.md"
write_plan "$PLAN_FILE"

PROSE_BODY="## Plan: Sample

### Reviewer notes — DO NOT TOUCH
This pre-marker prose was hand-edited by the reviewer.
Bullet:
- item A
- item B

<!-- run-plan:progress:start -->
**Phases completed:**
old content
<!-- run-plan:progress:end -->

### Design notes — also hand-edited
After-marker prose. Includes special characters: \"quotes\" and a /slash/.

---
Generated by /run-plan"

# Make the mock-gh script capture the --body-file content somewhere we
# can inspect. mock-gh.sh appends every invocation to _invocations.log
# with the FULL arg list, which includes the body-file path. But the
# helper's trap rm's the scratch dir on exit. So we use a different
# strategy: a wrapper gh mock that ALSO snapshots the --body-file content
# to $SD/captured-body-file before returning.
CAPTURE_MOCK="$WORK/mock-gh-capture-6.sh"
cat > "$CAPTURE_MOCK" <<EOF
#!/bin/bash
# Snapshot the --body-file content (if pr edit was called) then defer to
# the real mock-gh.sh.
if [ "\${1:-}" = "pr" ] && [ "\${2:-}" = "edit" ]; then
  for ((i=1; i<=\$#; i++)); do
    if [ "\${!i}" = "--body-file" ]; then
      next=\$((i+1))
      body_arg="\${!next}"
      if [ -f "\$body_arg" ]; then
        cp "\$body_arg" "$SD/captured-body-file"
      fi
      break
    fi
  done
fi
exec "$MOCK_GH" "\$@"
EOF
chmod +x "$CAPTURE_MOCK"

canned "$SD" pr_view 1 "$PROSE_BODY" "" 0
canned "$SD" pr_edit 1 "" "" 0

OUT=$(MOCK_GH_STATE_DIR="$SD" GH_BIN_OVERRIDE="$CAPTURE_MOCK" \
  bash "$SCRIPT" --pr 1003 --plan-file "$PLAN_FILE" --branch test 2>&1)
RC=$?

if [ "$RC" -ne 0 ]; then
  fail "6: preserve prose — exit expected 0, got $RC (output: $OUT)"
elif [ ! -f "$SD/captured-body-file" ]; then
  fail "6: preserve prose — captured body file missing"
else
  CAPTURED=$(cat "$SD/captured-body-file")
  # Assert all user-prose anchors survive.
  PROSE_FAIL=0
  for anchor in \
    "Reviewer notes — DO NOT TOUCH" \
    "This pre-marker prose was hand-edited" \
    "item A" \
    "item B" \
    "Design notes — also hand-edited" \
    "After-marker prose" \
    "Generated by /run-plan"
  do
    if ! grep -qF "$anchor" <<< "$CAPTURED"; then
      PROSE_FAIL=1
      fail "6: preserve prose — anchor missing: '$anchor'"
      break
    fi
  done
  # Assert the marker-enclosed region was actually replaced.
  if [ "$PROSE_FAIL" = "0" ]; then
    if grep -qF "old content" <<< "$CAPTURED"; then
      fail "6: preserve prose — old marker content not replaced"
    elif ! grep -qF "1: Setup" <<< "$CAPTURED"; then
      fail "6: preserve prose — new tracker row missing"
    else
      pass "6: preserve user prose outside markers"
    fi
  fi
fi

# ---------------------------------------------------------------
# Case 7: Plan file missing → ERROR → exit 1
# ---------------------------------------------------------------
SD=$(new_state_dir 7)
MISSING_PLAN="$WORK/does-not-exist.md"

OUT=$(MOCK_GH_STATE_DIR="$SD" GH_BIN_OVERRIDE="$MOCK_GH" \
  bash "$SCRIPT" --pr 1004 --plan-file "$MISSING_PLAN" --branch test 2>&1)
RC=$?

if [ "$RC" -ne 1 ]; then
  fail "7: plan missing — exit expected 1, got $RC (output: $OUT)"
elif ! grep -q "ERROR.*plan file not found" <<< "$OUT"; then
  fail "7: plan missing — missing ERROR line (output: $OUT)"
elif grep -q '^pr_view\|^pr_edit' "$SD/_invocations.log" 2>/dev/null; then
  fail "7: plan missing — gh should not be invoked at all"
else
  pass "7: plan file missing (ERROR, exit 1)"
fi

echo ""
echo "---"
printf 'Results: %d passed, %d failed (of %d)\n' "$PASS_COUNT" "$FAIL_COUNT" "$((PASS_COUNT + FAIL_COUNT))"
if [ "$FAIL_COUNT" -gt 0 ]; then exit 1; fi
exit 0
